- name: Ansible Copy crt  
  hosts: etcd
  vars_files:
    - ../etcd-vars/etcd-vars.yml
  tasks:
    - name: Copying the ca.pem
      become: true 
      copy:
        src: /tmp/{{PATH_KEYS}}/ca.pem
        dest: /etc/etcd/ca.pem
        mode: 0644
    - name: Copying the kubernetes.pem
      become: true
      copy:
        src: /tmp/{{PATH_KEYS}}/kubernetes.pem
        dest: /etc/etcd/kubernetes.pem
        mode: 0644
    - name: copying kubernetes-key.pem
      become: true
      copy:
        src: /tmp/{{PATH_KEYS}}/kubernetes-key.pem
        dest: /etc/etcd/kubernetes-key.pem
        mode: 0644
