- hosts: etcd
  remote_user: root
  become: yes
  vars_files:
    - ../etcd-vars/etcd-vars.yml
  tasks:
  - name: check if download cfssl exists
    stat:
      path: /usr/bin/cfssl
    register: downloadcfssl
  - name: check if download cfssljson exists
    stat:
      path: /usr/bin/cfssljson
    register: downloadcfssljson
  - name: download-cfssl
    get_url: url=https://pkg.cfssl.org/R1.2/cfssl_linux-amd64 dest=/usr/bin/cfssl
    when: downloadcfssl.stat.exists == False
  - name: download-cfssl-json
    get_url: url=https://pkg.cfssl.org/R1.2/cfssljson_linux-amd64 dest=/usr/bin/cfssljson
    when: downloadcfssljson.stat.exists == False
  - name : change-Permission
    file: path={{ item }}  mode="777"
    with_items:
      - /usr/bin/cfssl
      - /usr/bin/cfssljson

    when: inventory_hostname_short == FRIST_NODENAME
  - name: mkdir /tmp/{{ PATH_KEYS }}
    shell: mkdir -p /tmp/{{ PATH_KEYS }}
  - name: generate cert and Pkeys
    template: src=../template/genkeys.j2 dest=/tmp/genkeys.sh mode=0655
    when: inventory_hostname_short == FRIST_NODENAME
  - name: copy ca-csr
    template: src=../template/ca-csr.j2 dest=/tmp/{{ PATH_KEYS}}/ca-csr.json mode=0644
    when: inventory_hostname_short == FRIST_NODENAME
  - name: copy ca-config.json
    template: src=../template/ca-config.j2 dest=/tmp/{{ PATH_KEYS}}/ca-config.json  mode=0644
    when: inventory_hostname_short == FRIST_NODENAME
  - name: initialize-keys
    shell : cfssl gencert -initca /tmp/{{ PATH_KEYS }}/ca-csr.json | cfssljson -bare /tmp/{{ PATH_KEYS }}/ca
    when:  inventory_hostname_short == FRIST_NODENAME
  - name: execute script
    command: /bin/bash /tmp/genkeys.sh
    when:  inventory_hostname_short == FRIST_NODENAME
  - name: check if /etc/etcd directory
    stat:
      path: /etc/etcd/
    register: etcd
  - name: mkdir /etc/etcd/
    shell: mkdir /etc/etcd/
    when: etcd.stat.exists == False
