- hosts: k8s
  gather_facts: true
  vars_files:
    - ../vars/vars.yml
  tasks:
  - name: Check if nerdctl is installed
    command: nerdctl -v
    register: nerdctl_installed
    ignore_errors: yes

  - name: Install nerdctl if not installed
    shell: |
      curl -fsSL https://github.com/containerd/nerdctl/releases/download/v2.0.3/nerdctl-2.0.3-linux-amd64.tar.gz -o /tmp/nerdctl-linux-amd64.tar.gz
      tar -xzf /tmp/nerdctl-linux-amd64.tar.gz -C /tmp
      mv /tmp/nerdctl /usr/local/bin/nerdctl
    when: nerdctl_installed.rc != 0

  - name: Install required system packages
    apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
    loop:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    when: ansible_facts.packages[item] is not defined

  - name: Install containerd
    apt: name=containerd state=latest update_cache=yes
  - name: reset containerd
    shell: containerd config default > /etc/containerd/containerd.toml  && systemctl restart containerd
  - name: disable swap
    shell: swapoff -a
  - name: Disable SWAP in fstab
    replace:
      path: /etc/fstab
      regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
      replace: '# \1'
  - name: add run.sh
    template: src=../template/run.j2 dest=/opt/run.sh mode=655
    when: ansible_hostname == FRIST_NODENAME
