- hosts: k8sm1-t
  gather_facts: true
  vars_files:
    - ../vars/vars.yml
  tasks:
  - name: change dns
    shell: echo "nameserver {{ DNS_SERVER }}" > /etc/resolv.conf

  - name: Check if nerdctl is installed
    command: nerdctl -v 
    register: nerdctl_installed
    ignore_errors: yes

  - name: Install nerdctl if not installed
    shell: |
      curl -fsSL https://github.com/containerd/nerdctl/releases/download/v2.0.3/nerdctl-2.0.3-linux-amd64.tar.gz -o /tmp/nerdctl-linux-amd64.tar.gz
      tar -xzf /tmp/nerdctl-linux-amd64.tar.gz -C /tmp
      mv /tmp/nerdctl /usr/local/bin/nerdctl
    when: nerdctl_installed.rc != 0

  - name: Install required system packages
    apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
    loop:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    when: ansible_facts.packages[item] is not defined

  - name: Install containerd
    apt: name=containerd state=latest update_cache=yes
  - name:  /etc/apt/keyrings directory exists
    file:
      path: /etc/apt/keyrings
      state: directory
      mode: '0755'
  - name: add-gpg-k8s
    shell:  curl  -fsSL   {{GPG_KEY_K8S}} | sudo gpg --dearmor --yes -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  - name: add-repo-k8s
    shell: echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] {{REPO_URL}}' | sudo tee /etc/apt/sources.list.d/kubernetes.list 
  - name: Install Kubernetes tools
    apt:
      name:
        - kubelet={{VERSION}}
        - kubectl={{VERSION}}
        - kubeadm={{VERSION}}
      state: present
  - name: disable swap
    shell: swapoff -a  
  - name: Disable SWAP in fstab 
    replace:
      path: /etc/fstab
      regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
      replace: '# \1'
  - name: add run.sh
    template: src=../template/run.j2 dest=/opt/run.sh mode=655
    when: ansible_hostname == FRIST_NODENAME
