- hosts: k8s
  remote_user: root
  vars_files:
    - ../vars/vars.yml
  tasks:
  - name: change dns 
    shell: echo nameserver {{DNS_SERVER}}  > /etc/resolv.conf
  - name: check  images 
    shell: nerdctl -n k8s.io images  | grep kube-proxy || true
    register: images
  - name: pull-config-k8s
    shell: kubeadm config images pull
    when: images.stdout.find('k8s.gcr.io/kube-proxy') == -1
  - debug: msg="{{images.stdout_lines}}"
