- hosts: k8s
  remote_user: root
  tasks:
    - name: sysctl parameters in /etc/sysctl.conf
      shell: cat /etc/sysctl.conf
      register: sysctl_content

    - name: set sysctl parameters
      shell: |
        echo "####ADDED BY ANSIBLE####" >> /etc/sysctl.conf
        echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf
        echo "net.ipv6.conf.default.disable_ipv6 = 1" >> /etc/sysctl.conf
        echo "fs.file-max = 65535" >> /etc/sysctl.conf
        echo "net.ipv4.ip_local_port_range = 1024 65000" >> /etc/sysctl.conf
        echo "net.core.somaxconn = 32768" >> /etc/sysctl.conf
        echo "vm.swappiness=10" >> /etc/sysctl.conf
        echo "vm.vfs_cache_pressure=10" >> /etc/sysctl.conf
        sysctl -p
      when: "'####ADDED BY ANSIBLE####' not in sysctl_content.stdout"

    - name: kernel modules (overlay, br_netfilter) if not loaded
      shell: |
        modprobe overlay
        modprobe br_netfilter
      ignore_errors: yes

    - name: kernel modules are loaded on boot
      lineinfile:
        path: /etc/modules
        line: "{{ item }}"
        create: yes
      loop:
        - overlay
        - br_netfilter
      when: "'overlay' not in lookup('file', '/etc/modules') or 'br_netfilter' not in lookup('file', '/etc/modules')"
